name: habit_tracker_app
description: A new Flutter project.



publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
 
  adaptive_action_sheet: ^2.0.2
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.4
  flutter_launcher_icons: ^0.10.0
  flutter_svg: ^1.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  modal_bottom_sheet: ^2.1.0
  page_flip_builder: ^0.1.3
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  hive_generator: ^1.1.3

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  # https://github.com/fluttercommunity/flutter_launcher_icons/issues/144
  image_path_ios: "assets/images/app-icon.png"
  image_path_android: "assets/images/app-icon.png"
  adaptive_icon_background: "assets/images/app-icon-background.png"
  adaptive_icon_foreground: "assets/images/app-icon.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

  fonts:
  - family: Manrope
    fonts:
      - asset: assets/fonts/Manrope-Regular.ttf
      - asset: assets/fonts/Manrope-Bold.ttf
        weight: 900
      - asset: assets/fonts/Manrope-light.ttf
        weight: 300
      - asset: assets/fonts/Manrope-Medium.ttf
        weight: 500
      - asset: assets/fonts/Manrope-SemiBold.ttf
        weight: 700